### ISSUE TITLE
Is there any way to flip the Y coordinate?

### ISSUE THREAD

**Issue by smukherjee2016** [emoon/rust_minifb#248]
Hi there, thanks so much for the wonderful crate! 

I am currently using this crate with my ray tracer I'm implementing in Rust, but due to difference in coordinate systems between my ray tracer and OpenGL (possibly), the image comes up as flipped:

![image](https://user-images.githubusercontent.com/6712929/119793519-a1830680-bf11-11eb-9e15-1c47e37ddac7.png)

Is it possible to have an option to fix this by some configuration option? Thanks again!

**Comment by emoon** [comment]
Hey and thanks!

While it would be possible to implement such feature I'm not sure if it's worth the added complexity in this case. As the data comes from OpenGL it's possible to flip one of the sign for -y in your projection matrix (I think, not fully sure of your setup) to allow it to be displayed the other way around.

Otherwise a different loop to copy the data row by row backwards would do the trick as well.
